### ISSUE TITLE
Retry attempts

### ISSUE THREAD

**Issue by seanmavley** [topac/rmega#18]
I noticed rmega doesn't have a retry attempt feature. Any network interruption causes download to stop.
I'm on one of the worst networks on earth, and any network-related interruptions causes the the error: `ERROR: Unexpected data length` to be thrown.

A way to specify retry attempts will be priceless, and I'll be the first to set mine at 2M retries!

**Comment by topac** [comment]
Hi, indeed it has a retry attempt feature: 
https://github.com/topac/rmega/blob/master/lib/rmega/net.rb#L6
```max_retries``` is 10 by default but right now you can't change it through the options of ```rmega-dl``` but only if you use the rmega API in a ruby script.

I'm assuming that you're using the ```rmega-dl``` command. Can you try to launch it with the ```--debug``` in order to give me more details about your error? Thanks

**Comment by manas-124** [comment]
Hi, 
I am also facing the same issue. Please find the log file attached.
[log.txt](https://github.com/topac/rmega/files/439721/log.txt)
